name: "Setup TypeScript Scripts"
description: "Build TypeScript scripts"
inputs:
  path:
    description: 'Path to the scripts'
    required: true
runs:
    using: "composite"
    steps:
        - name: Setup environment
          shell: bash
          run: |
              test -f .nvmrc || exit 0
              NODE_VERSION=$(cat .nvmrc | xargs)
              echo "node_version=$NODE_VERSION" >> $GITHUB_ENV

        - name: Setup node
          uses: actions/setup-node@v3
          with:
              node-version: ${{ env.node_version }}
              cache: npm
              cache-dependency-path: ${{ inputs.path }}/package-lock.json

        - name: Install dependencies
          shell: bash
          run: |
              cd ${{ inputs.path }}
              npm ci

        - name: Build TypeScript scripts
          shell: bash
          run: |
              cd ${{ inputs.path }}
              npm run build
