name: 'Run TypeScript Script'
description: 'Runs a TypeScript script using actions/github-script'
inputs:
  function-name:
    description: 'Name of the function to call'
    default: ""
  bundle:
    description: 'Path to the bundle file'
    default: "../out/out.js"
runs:
  using: 'composite'
  steps:
    - name: 'Execute script'
      uses: 'actions/github-script@v6'
      with:
        script: |
          const path = __original_require__('path');
          const { $INPUT_FUNCTION_NAME, $INPUT_BUNDLE } = process.env;
          const scriptPath = path.resolve(process.cwd(), $INPUT_BUNDLE);
          const scriptModule = __original_require__(scriptPath);
          const func = scriptModule[$INPUT_FUNCTION_NAME];
          if (typeof func !== 'function') {
            throw new Error(`Function "${$INPUT_FUNCTION_NAME}" not found in ${INPUT_BUNDLE}.`);
          }
          await func(github, context, core);
