name: 'Run TypeScript Script'
description: 'Runs a TypeScript script using actions/github-script'
inputs:
  function-name:
    description: 'Name of the function to call'
    default: ""
  bundle-path:
    description: 'Path to the bundle file'
    default: "./.github/ts-actions/out/out.js"
runs:
  using: 'composite'
  steps:
    - name: 'Execute script'
      uses: 'actions/github-script@v6'
      with:
        script: |
          const { $INPUT_FUNCTION_NAME, $INPUT_BUNDLE_PATH } = process.env;
          core.info(`Running ${$INPUT_FUNCTION_NAME} from ${$INPUT_BUNDLE_PATH}`);
          const scriptModule = require($INPUT_BUNDLE_PATH);
          const func = scriptModule[$INPUT_FUNCTION_NAME];
          if (typeof func !== 'function') {
            throw new Error(`Function "${$INPUT_FUNCTION_NAME}" not found in ${INPUT_BUNDLE_PATH}.`);
          }
          await func(github, context, core);
