on:
    pull_request:
      types:
        - opened
        - reopened
        - labeled
        - synchronize

jobs:
    self-document:
        name: ${{ contains(github.event.pull_request.labels.*.name, 'bug') && 'bug' || 'feature' }}
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3
