name: debug
on:
  push:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - synchronize

  schedule:
    - cron: "*/15 * * * *"

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"
          [ $((RANDOM % 2)) -eq 0 ]
