name: debug
on:
  push:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  debug:
    name: ${matrix.name} ${matrix.target}
    runs-on: ubuntu-latest
    strategy:
        fail-fast: false
        matrix:
            target: ["a", "b"]

            include:
                - name: default
                - name: candidate

    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"
          pwd
          [ $((RANDOM % 2)) -eq 0 ]
