name: empty env var
on:
  push:

jobs:
  empty:
    runs-on: ubuntu-latest
    steps:
      - name: debug
        env:
            NULL_VALUE: ${{ null }}
            EMPTY_VALUE: ""
        run: |
          env | grep NULL_VALUE && echo "NULL_VALUE present" || true
          [ -z "$NULL_VALUE" ] && echo "NULL_VALUE empty" || true
          env | grep EMPTY_VALUE && echo "EMPTY_VALUE present" || true
          [ -z "$EMPTY_VALUE" ] && echo "EMPTY_VALUE empty" || true

