name: fail
on:
  pull_request:
    types:
      - opened
      - synchronize

  schedule:
    - cron: "*/15 * * * *"

jobs:
  fail:
    runs-on: ubuntu-latest
    steps:
      - name: fail
        run: |
          false
