# debug
name: label-event
on:
  pull_request:
    types:
      - labeled

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: debug
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
