name: Log Retrieval Workflow

on:
  pull_request:


jobs:
  job1:
    strategy:
      matrix:
        config:
          - 1
          - 2
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Run Commands for Matrix ${{ matrix.config }}
        run: |
          echo "Executing commands for matrix element ${{ matrix.config }}"
          echo "This will generate logs for matrix element ${{ matrix.config }}"

  retrieve-logs:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Retrieve Logs for Each Matrix Job
        env:
          GH_TOKEN: ${{ github.token }}
          NEEDS: job1
        run: |
          gh api -X GET repos/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID/jobs
          JOB_IDS=$(gh api -X GET repos/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID/jobs --jq '[.jobs[] | select(.name=="${{ env.NEEDS }}") | .id]')
          echo "Job IDs: $JOB_IDS"
          
          # Install jq for parsing JSON
          sudo apt-get install jq

          for JOB_ID in $(echo $JOB_IDS | jq -r '.[]'); do
            echo "Retrieving logs for Job ID: $JOB_ID"

            # Get the logs URL
            LOGS_URL=$(curl -s -H "Authorization: token $GH_TOKEN" \
                      "https://api.github.com/repos/$GITHUB_REPOSITORY/actions/jobs/$JOB_ID/logs" -D - \
                      | grep location | cut -d " " -f 2 | tr -d '\r')

            echo "Logs URL: $LOGS_URL"

            # Download the logs
            curl -L $LOGS_URL -o "logs_job_${JOB_ID}.txt"

            # Optional: Display the logs
            cat "logs_job_${JOB_ID}.txt"
          done
