name: mergeable
on:
  status:

env:
  LABEL: mergeable

jobs:
  process-mergeable-check:
    runs-on: ubuntu-latest
    if: github.event_name == 'status'
    steps:
      - uses: actions/github-script@v3
        with:
          script: |
            const prs = await github.repos.listPullRequestsAssociatedWithCommit({
              ...context.repo,
              commit_sha: context.payload.sha
            })
            if (prs.data.length === 0) {
              return;
            }
            prs.data.forEach(function(pr) {
              if (pr.state != 'open'){
                continue;
              }
              console.log('html_url=${pr.html_url} mergeable=${pr.mergeable} mergeable_state=${pr.mergeable_state}`)
              if (pr.mergeable == 'true') {
                await github.issues.addLabels({
                  ...context.repo,
                  issue_number: pr.number,
                  labels: [process.env.LABEL]
                })
              } else {
                try {
                  await github.issues.removeLabel({
                    ...context.repo,
                    issue_number: pr.number,
                    name: process.env.LABEL
                  })
                } catch (e) {
                  if (e.status != 404) {
                    throw(e);
                  }
                }
              }
            });
