name: needs demo
on:
  pull_request:

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: fail
        run: |
          false
  run-test:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: skip
        run: |
          echo not run
  required:
    name: test
    needs: [setup, run-test]
    if: failure() || cancelled()
    runs-on: ubuntu-latest
    steps:
      - name: Dependent jobs failed or were cancelled
        run: exit 1    
