name: needs demo
on:
  pull_request:

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: fail
        run: |
          false
  test:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: skip
        run: |
          echo not run
