name: needs demo
on:
  pull_request:

jobs:
  fail:
    runs-on: ubuntu-latest
    steps:
      - name: fail
        run: |
          false
  skip:
    runs-on: ubuntu-latest
    needs: fail
    steps:
      - name: skip
        run: |
          echo not run
  skip2:
    runs-on: ubuntu-latest
    needs: skip2
    steps:
      - name: skip
        run: |
          echo not run
