name: required pass
on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize

  schedule:
    - cron: "*/15 * * * *"

jobs:
  pass:
    runs-on: ubuntu-latest
    steps:
      - name: sleep
        run: |
          sleep 30
          true
      - name: pass
        run: |
          true
