name: required pass
on:
    pull_request:
        types:
            - opened
            - synchronize

    schedule:
        - cron: "*/15 * * * *"

jobs:
    pass:
        runs-on: ubuntu-latest
        steps:
            - name: sleep
              run: |
                  sleep 30
                  true
            - name: pass
              run: |
                  true
