name: pr
on:
  pull_request:
    types:
      - synchronize
      - opened
jobs:
  status:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.repos.createCommitStatus({
              owner:   context.repo.owner,
              repo:    context.repo.repo,
              sha:     context.sha
              state:   'pending',
              context: 'test',
            });

      - uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const result = await github.repos.listCommitStatusesForRef({
              owner:   context.repo.owner,
              repo:    context.repo.repo,
              sha:     context.sha,
            });
            console.log(result)

      - uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.repos.createCommitStatus({
              owner:       context.repo.owner,
              repo:        context.repo.repo,
              sha:         context.sha
              state:       'success',
              description: 'some string',
              context:     'test',
            });

      - uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const result = await github.repos.listCommitStatusesForRef({
              owner:   context.repo.owner,
              repo:    context.repo.repo,
              sha:     context.sha,
            });
            console.log(result)
