name: pull_request.syncronize
on:
  pull_request:
    types:
      - labeled
      - unlabeled
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: first
      run: |
        echo "Ref: $GITHUB_REF"
        echo "Sha: $GITHUB_SHA"
