name: conflict
on:
  pull_request:
    types:
      - synchronize
jobs:
  conflict:
    runs-on: ubuntu-latest
    steps:
      - name: conflict
        env:
          FOO: bar
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"; echo $FOO
