name: pull_request.synchronize
on:
  pull_request:
    types:
      - synchronize
jobs:
  uptime:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
