name: pull_request.synchronize
on:
  pull_request:
    types:
      - synchronize
jobs:
  fourth:
    runs-on: ubuntu-latest
    steps:
    - name: debug
      run: |
        echo "Ref: $GITHUB_REF"
        echo "Sha: $GITHUB_SHA"
