name: pr
on:
  pull_request:
    types:
      - synchronize
      - opened
jobs:
  create-status:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            await github.repos.createCommitStatus({
              owner:   context.repo.owner,
              repo:    context.repo.repo,
              sha:     context.payload.pull_request.head.sha,
              state:   'pending',
              context: 'test',
            });

      - uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            await new Promise(r => setTimeout(r, 30000));
            await github.repos.createCommitStatus({
              owner:       context.repo.owner,
              repo:        context.repo.repo,
              sha:         context.payload.pull_request.head.sha,
              state:       'success',
              description: 'good string',
              context:     'test',
            });

  wait-for-status-with-matching-description:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v3
        timeout-minutes: 3
        id: statuses
        env:
          CONTEXT_INCLUDES: test
          DESCRIPTION_INCLUDES: good string
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          result-encoding: string
          script: |
            while (true) {
              const result = await github.repos.getCombinedStatusForRef({
                owner:   context.repo.owner,
                repo:    context.repo.repo,
                ref:     context.payload.pull_request.head.sha,
              });

              const matchesContext = (status) => status.context.includes(process.env.CONTEXT_INCLUDES)

              const hasGoodDescription = (status) => status.description.includes(process.env.DESCRIPTION_INCLUDES)

              const success = (status) => status.state == 'success'

              const failed = (status) => status.state == 'failed' || status.state == 'error'

              const matchingStatuses = result.data.statuses.filter(matchesContext);
              if (Array.isArray(matchingStatuses) && matchingStatuses.length > 0) {
                if (matchingStatuses.every(success)) {
                  if (matchingStatuses.every(hasGoodDescription)) {
                    console.log(`all statuses matching ${process.env.CONTEXT_INCLUDES} have succeeded and have output matching ${process.env.DESCRIPTION_INCLUDES}`);
                    return 'matched';
                  } else {
                    console.log(`all statuses matching ${process.env.CONTEXT_INCLUDES} have succeeded, but some don't match ${process.env.DESCRIPTION_INCLUDES}`);
                    break;
                  }
                } 

                // fail fast if a matching status has failed
                if (matchingStatuses.some(failed)) {
                  console.log(`a status matching ${process.env.CONTEXT_INCLUDES} failed`);
                  break;
                }

                // explain why we're still processing
                console.log(`statuses matching ${process.env.CONTEXT_INCLUDES} found, not all done yet`);
              } else {
                console.log(`No statuses matching ${process.env.CONTEXT_INCLUDES} found yet`);
              }

              await new Promise(r => setTimeout(r, 2000));
            }

      - uses: actions/github-script@v3
        if: steps.statuses.outputs.result == 'true'
        env:
          LABEL: matched
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            await github.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: [process.env.LABEL]
            })

      - uses: actions/github-script@v3
        if: steps.statuses.outputs.result != 'true'
        env:
          LABEL: matched
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            try {
              await github.issues.removeLabel({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                name: process.env.LABEL
              })
            } catch (e) {
              if (e.status != 404) {
                throw(e);
              }
            }
