name: Required

on:
  workflow_run:
    workflows:
      - debug
      - fail
    types:
      - completed

jobs:
  success:
    if: github.event.workflow_run.event == 'pull_request'
    name: Create appropriate status
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        env:
          RUN_ID: ${{ github.event.workflow_run.id }}
        with:
          retries: 3
          script: |
            const workflow = await github.rest.actions.getWorkflowRun({
              ...context.repo,
              run_id: process.env.RUN_ID
            });

            // list all workflows runs for the same head_sha
            const workflowRuns = await github.rest.actions.listWorkflowRunsForRepo({
              ...context.repo,
              head_sha:      workflow.data.head_sha
            });

            // loop through them all
            for (const workflowRun of workflowRuns.data.workflow_runs) {
              // Skip unless the run name matches 'required' or something?
              // workflowRun.name.match(/required/i)


              // bail and return failure if any have failed
              if (workflowRun.conclusion == 'failure') {
                await github.rest.repos.createCommitStatus({
                  ...context.repo,
                  sha:         workflow.data.head_sha,
                  state:       'failure',
                  context:     'required',
                  description: workflowRun.name + has + workflowRun.conclusion + '.',
                  target_url:  workflowRun.html_url
                });
                return;
              }

              // bail silently if builds are in progress somehow
              if (workflowRun.conclusion != 'success') {
                return
              }
            }

            // report success if all observed workflows have succeeded
            await github.rest.repos.createCommitStatus({
              ...context.repo,
              sha:         workflow.data.head_sha,
              state:       'success',
              context:     'required',
              description: 'All workflows have succeeded.',
              target_url:  'https://github.com/' + context.repository + '/commit/' +  workflow.data.head_sha + '/checks'
            });
