name: Required

on:
  workflow_run:
    workflows:
      - debug
      - fail
    types:
      - completed

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  success:
    if: >-
      github.event.workflow_run.event == 'pull_request' && github.event.workflow_run.conclusion == 'success'
    name: Create pending or success status
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        env:
          RUN_ID: ${{ github.event.workflow_run.id }}
        with:
          retries: 3
          script: |
            const workflow = await github.rest.actions.getWorkflowRun({
              ...context.repo,
              run_id: process.env.RUN_ID
            });
            await github.rest.repos.createCommitStatus({
              ...context.repo,
              sha:         workflow.data.head_sha,
              state:       'pending',
              context:     'required',
              description: 'Some required builds have succeeded',
              target_url:  'https://github.com/${{ github.repository }}/commit/${{ workflow.data.head_sha }}/checks'
            });

  failure:
    if: >-
      github.event.workflow_run.event == 'pull_request' && github.event.workflow_run.conclusion != 'success'
    name: Create failure status
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        env:
          RUN_ID: ${{ github.event.workflow_run.id }}
        with:
          retries: 3
          script: |
            const workflow = await github.rest.actions.getWorkflowRun({
              ...context.repo,
              run_id: process.env.RUN_ID
            });
            await github.rest.repos.createCommitStatus({
              ...context.repo,
              sha:         workflow.data.head_sha,
              state:       'failure',
              context:     'required',
              description: 'Some required builds have failed',
              target_url:  'https://github.com/${{ github.repository }}/commit/${{ workflow.data.head_sha }}/checks'
            });
