name: test
on:
  pull_request:
    types:
      opened
      - synchronize
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: debug
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
