name: Run TypeScript Actions

on:
    pull_request:

jobs:
    run_scripts:
        runs-on: ubuntu-latest
        steps:
            - name: Dump GitHub context
              env:
                  GITHUB_CONTEXT: ${{ toJson(github) }}
              run: |
                  echo "$GITHUB_CONTEXT"

            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Setup TypeScript scripts
              uses: ./.github/workflows/setup-ts-scripts

            - name: Run prNumber
              id: prNumber
              uses: ./.github/workflows/run-ts-script
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  script: prNumber

            - name: Validate result
              run: |
                  echo "PR number is ${{ steps.prNumber.outputs.result }}"
