name: warm caches
on:
    push:
        branches:
            - main
    schedule:
        - cron: "30 5,17 * * *"
jobs:
    warm_caches:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Setup TypeScript scripts
              uses: ./.github/workflows/setup-ts-scripts
