name: workflow_run event bug

on:
  workflow_run:
    workflows:
      - debug
    types:
      - completed
    branches:
      - main

run-name: ${{ github.event.workflow_run.event }} ${{ join(github.event.workflow_run.pull_requests.*.number || fromJson('[]'),'') }}

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"
